kind: pipeline
name: default

steps:
- name: build-site
  image: node:20-alpine
  commands:
  - yarn
  - yarn build

- name: push-registry
  image: plugins/docker
  settings:
    repo: registry.max-heidinger.de/max-heidinger.de
    registry: registry.max-heidinger.de
    tags:
      - latest
      - ci-${DRONE_BUILD_NUMBER}
    username:
      from_secret: tac_username
    password:
      from_secret: tac_password
  when:
    branch:
    - master
    - develop
    event:
      exclude:
      - pull_request

- name: update-deployment
  image: plugins/webhook
  settings:
    urls: https://portainer.max-heidinger.de/api/webhooks/3aec3046-1a5c-4981-961d-d2d79d84054d
    username:
      from_secret: tac_username
    password:
      from_secret: tac_password
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
