kind: pipeline
name: default

steps:
- name: build-site
  image: node:22-alpine
  commands:
  - yarn
  - yarn build

- name: push-registry
  image: plugins/docker
  settings:
    repo: registry-castor.max-heidinger.de/max-heidinger.de
    registry: registry-castor.max-heidinger.de
    tags:
      - latest
      - ci-${DRONE_BUILD_NUMBER}
    username:
      from_secret: tac_username
    password:
      from_secret: tac_password
  when:
    branch:
    - master
    - develop
    event:
      exclude:
      - pull_request

- name: update-deployment
  image: plugins/webhook
  settings:
    urls: https://portainer-castor.max-heidinger.de/api/webhooks/ca952cf1-f7df-4f88-b9b2-f4d10083386d
    username:
      from_secret: tac_username
    password:
      from_secret: tac_password
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
